eteran/c-vector

.gitignore, .vscode/settings.json, CMakeLists.txt, README.md, cvector.c, cvector.h, example.c
1. Use CMake as project making system.
2. Rewrite marco signatures in order to reduce ambiguity.
For example, `vector_set_capacity(vec, size)` is renamed to `cvector_set_capacity(vec, size)` to reduce the risk of clashing with other libraries.
Also, marco `LOGARITHMIC_GROWTH` is renamed to `CVECTOR_LOGARITHMIC_GROWTH` for the same reason.
3. `README.md` and `exmaple.c` are edited to suit the new source file.
=> Modernization and ambiguity reduction

cvector.h
I added a function `cvector_copy()` to solve #8 . I tried to use `memcpy()`, but it didn't work, so I use `cvector_push_back()`. The result is whether I make any change to the vector `from`, the vector `to` still remains the same.
=> cvector.h: added cvector_copy() function

cvector.h, cvector_utils.h, test.c
This is a handy function for freeing each elements in case they are also allocated in the heap for example like string, and only using `cvector_free` won't each elements from the heap
```
#define CVECTOR_LOGARITHMIC_GROWTH
#include "cvector.h"
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[]) {
char str_1[] = "hello world";
char str_2[] = "good bye world";
char str_3[] = "not today" ;
cvector_vector_type(char*) v = NULL;
cvector_push_back(v, strdup(str_1));
cvector_push_back(v, strdup(str_2));
cvector_push_back(v, strdup(str_3));
if (v) {
size_t i;
for (i = 0; i < cvector_size(v); ++i) {
printf("v[%zu] = %s\n", i, v[i]);
}
}
cvector_free(v);
// cvector_free_and_free_elements(v,free);
return 0;
}
```
in the example above, valgrind tells that there are memory leak when …
=> add cvector_free_and_free_elements

cvector_utils.h
Add for loop header macro `cvector_for_each_in` to mimic frequently used range-based for cvectors. With this macro, it might be a good idea to remove `cvector_for_each` and `cvector_free_each_and_free`, because they break C89 compatibility. Declaring a variable is not permitted in C89. It might be a good idea to merge `cvector_for_each_in` if the other macros are removed, because cvector_utils.h only contains one macro.
Example usage of `cvector_for_each_in`:
```
int *it;
cvector_vector_type(int) v = NULL;
cvector_push_back(v, 10);
cvector_push_back(v, 12);
cvector_for_each_in(it, v) {
printf("%d\n", *it);
}
```
The example prints out all members of cvector v.
=> Add macro cvector_for_each_in

README.md, cvector.h, cvector_utils.h
Add function pointer that mimcs the element's destructor. The vector may be used with complex data structures that hold dynamically allocated memory. To prevent leaking this memory when elements are removed, I introduce a new field at the start of the cvector meta-data called `elem_destructor()`. Each time a element is removed, the function is called to prevent memory leaks. Initially, the function pointer is set to NULL. If that's the case, then no destructor is called, ensuring backwards compatibility.
This PR also already contains the commits from [PR 36](https://github.com/eteran/c-vector/pull/36), so please land this one first.
Here is the test I wrote to check the functionality:
```
jh@jh-ThinkPad-X250:~/GameDev/c-vector
$ cat test_changes.c
#include <stdio.h>
#include "cvector.h" …
```
=> Feature: element destructor

cvector.h
For some people who want to use this library on the other project by just copying the file, need to add copyright on the top of the file.
If the copyright and the license are already specified on the top of the file, this library can be much easier to be used.
I'm trying to use cvector.h on other project.
https://github.com/iovisor/bcc/pull/4120
And one reviewer recommend me to add copyright notice on the cvector.h file.
I thinks this request is reasonable and it would be better to add the copyright notice on the main project.
=> Add copyright and license on the top of the cvector.h file

cvector.h
The second parameter of `cvector_reserve` is `n` on the description but `capacity` on the source code.
Change it to `n` for unification.
It could be possible to change it to `capacity` for unification, I guess.
=> Change parameter name same as description

cvector.h, unit-tests.c
* fix segfault caused by passing destructed value to `cvector_free` with `cvector_destructor`
* add unit test for dereferencing vector in cvector_destructor
-----
So, the problem was caused by code resembling the following:
```c
cvector_free(*vec_ptr);
```
This code expands to:
```c
&*vec_ptr[i]
```
This leads to an erroneous memory access and results in a segmentation fault.
=> Fix destructor dereferencing

cvector.h, example.c, test.c, unit-tests.c
This adds a `cvector_iterator(type)` to mimic `std::vector<type>::iterator`. Since it ends up being very similar to the original vector definition, I believe the syntax looks a bit nicer. It also ends up matching a bit of what C++ implements too, with the `::iterator` member.
I believe it's a bit easier to read.
=> Add cvector_iterator

cvector.h
This change also only includes the C library headers only if the functions are required.
=> Allow overriding C's assert(), memcpy(), and memmove()

cvector.h, example.c, unit-tests.c
I'm not sure if this is something you're interested in, but I find it makes the code a bit more readable...
``` c
cvector(int) v = NULL;
```
=> Add cvector() syntactic sugar alias macro for cvector_vector_type()

CMakeLists.txt, cvector.h, unit-tests.c
This applies warnings-as-errors in the build, and fixes the comparision warnings as listed below.
```
In file included from /c-vector/example.c:8:
/c-vector/example.c: In function ‘main’:
/c-vector/cvector.h:422:18: error: comparison of unsigned expression in ‘< 0’ is always false [-Werror=type-limits]
422 |     ((vec) ? ((n < 0 || n >= cvector_size(vec)) ? NULL : &(vec)[n]) : NULL)
|                  ^
/c-vector/cvector.h:436:41: note: in expansion of macro ‘cvector_at’
436 |     ((vec) ? ((cvector_size(vec) > 0) ? cvector_at(vec, cvector_size(vec) - 1) : NULL) : NULL)
|                                         ^~~~~~~~~~
/c-vector/example.c:41:17: note: in expansion of macro ‘cvector_back’
41 |     int *back = cvector_back(v);
|                 ^~~~~~~~~~~~
/c-vector/cvector.h:422:18: …
```
=> Fix strict warnings

README.md, cvector.h
I'm unsure if this is something that you're considering, but I've added a table with comparison equivalents to `std::vector` at the bottom of README.md. May be a useful reference when looking for implementation details.
Also adds some `@internal` doxygen notes for the functions that are internal.
[Preview](https://github.com/RobLoach/c-vector/tree/api-docs?tab=readme-ov-file#api)
=> Add API documentation comparison to `std::vector`

CMakeLists.txt, cvector.h, example.c, unit-tests.c
After I closed my issue, I suddenly had an idea.
Now, `cvector_at` can be used as follow:
```c
#include "cvector.h"
#include <stdio.h>
#include <assert.h>
int main(void) {
cvector(int) v = NULL;
cvector_push_back(v, 1);
printf("%d\n", cvector_at(v, 0)); // get value
cvector_at(v, 0) = 2; // set value
printf("%d\n", cvector_at(v, 0));
// printf("%d\n", cvector_at(v, 1)); // assert fail
return 0;
}
```
=> refactor cvector_at

cvector.h, example.c, unit-tests.c
It is more idiomatic for cvector_at to return a reference. This allows mutability of the element at the given index, and allows for the existence of an element at a given index to be expressed in a different way than explicitly checking the size of the vector.
This also corrects the documentation for cvector_front and cvector_back, as those were still documented as returning references, not values.
=> Revert cvector_at changes

README.md, cvector.h, example.c, test.c, unit-tests.c
In my own usage and in the examples I can find with using this library, it is more common to want to use the logarithmic growth algorithm than the linear growth algorithm. This is also the default (or only option) with vector and dynamic array data structures that are available in other programming languages. Setting the logarithmic algorithm to the default will reduce the burden on library users to define a special value in each compilation unit they use the library, and reduce the risk that they will forget to define it and lose performance.
This change is backwards compatible with any existing programs that defined the CVECTOR_LOGARITHMIC_GROWTH value; their program will continue to operate as intended, and they can remove the definition if/when they want.
This change *will* modify the …
=> Replace CVECTOR_LOGARITHMIC_GROWTH with CVECTOR_LINEAR_GROWTH

unit-tests.c
- free `a` and `b` in `vector_swap`  
- use destructor for `data_t` elements  
- unify element destructors (unrelated bonus)
=> Fix memory leaks in unit tests

.gitattributes
The .h extension is ambiguous. However, it's quite misleading if GitHub's Linguist tags the whole repo as C++ because of that.
=> make GitHub recognize headers as C code

cvector.h, cvector_utils.h
- by default, Doxygen only adds a documentation to files that are commented with a `file` command
- comments have to follow the Doxygen syntax
=> properly interact with Doxygen

cvector.h
Allocation, reallocation, and deallocation functions must not belong to different libraries. Ensure that either all or none of them are overridden.
=> ensure harmonized memory management functions

cvector.h
Insertion of a preliminary cast to `void *` into `cvector_vec_to_base` will silence this compiler warning.
=> avoid cast-align warnings

cvector.h
Even with cryptic variable names we cannot fully avoid to shadow variables in user code. However, we absolutely can use different variable names in the API to avoid shadowing when macros are nested.
=> avoid variable shadowing
